name: todo_app_firestore_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.0
  #cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  share: ^0.6.2+3


  # firebase integration
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  form_field_validator: ^1.1.0


  # slidable
  flutter_slidable: ^0.5.7

  # state management
  provider: ^4.3.2+2
  #provider: ^6.0.0

  curved_navigation_bar:
  google_fonts: ^1.1.0
  http: ^0.12.1
  logger: ^0.9.1
  image_picker: ^0.6.7+4
  json_annotation:
  material_floating_search_bar: ^0.2.6
  webview_flutter: ^2.0.13
  flutter_svg: ^0.19.0
  flutter_clean_calendar: ^1.1.0

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/img/
   - assets/icons/
  
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
        - asset: assets/fonts/bebas_bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700





